# Generated by Django 5.0 on 2024-02-10 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='amount',
        ),
    ]
