# Generated by Django 5.0 on 2024-02-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0002_remove_productorder_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='_amount',
            field=models.IntegerField(default=1),
        ),
    ]
